### ISSUE TITLE
SRAM no longer saving or loading

### ISSUE THREAD

**Issue by DoctorWolfenstein** [libretro/opera-libretro#96]
For example, select 'Big Game Mode' in Road Rash, go to 'Restroom' then save. Go to load the game, and all slots still show as 'Empty'. No .srm file is saved, and existing .srm files from previous versions of the core are not loaded either. This is using the Linux version of the core from 25th June 2018.

**Comment by trapexit** [comment]
To confirm: you're using "per game" saves?

**Comment by DoctorWolfenstein** [comment]
Yes, 'NVRAM Storage' in the options is set to 'per game'. I have RetroArch set to sort saves into per-core folders, and it will create the '4DO' sub-folder, but doesn't create any .srm files within.

Keep up the awesome work! :-)

**Comment by trapexit** [comment]
It looks like a Retroarch issue. I'm working with the team to figure out a solution. For the time being you could use shared nvram which is outside retroarch's control.

**Comment by obenguerah** [comment]
shared nvram are broken as well, see: https://github.com/libretro/opera-libretro/issues/144

**Comment by trapexit** [comment]
These are entirely different problems. #144 is due to how the core is trying to atomically swap out files. This problem is due to Retroarch itself.

**Comment by Sanaki** [comment]
Just found out about this the hard way. Is there any clue what's causing per-game saves to fail? I can just leave it on shared for now, but I'd imagine I'll run out of space that way in time.

**Comment by arrowgent** [comment]
ooohhh.......i figured something
i was using `FZ-10 (U)` bios, and this was failing
switching disc1 & disc2 (saving overrides) to `FZ-1 (U)` fixed the save game issue on disc 2
repeated testing with disc 1 savestate confirmed this working

**Comment by trapexit** [comment]
Perhaps a bios compatibility issue. Or emulation bug. I can look into it at some point but that is unrelated to this ticket which should be closed as it was fixed in RA a while back it seems.

**Comment by DoctorWolfenstein** [comment]
Unfortunately this issue isn't resolved. I have re-installed the OS, RetroArch and Opera core from scratch and the behaviour is the same as the original issue from 2018. Setting saves to 'shared' successfully creates '3DO.nvram' in the 'system' folder, but setting saves to 'per game' results in no files created in the 'saves' folder. Road Rash is unable to create a save at all when set to 'per game'. Other cores are working fine.

-Ubuntu MATE 20.04.3
-RetroArch 1.9.11 (from official stable PPA)
-Opera 1.0.0 7369aa8

**Comment by trapexit** [comment]
Apologies. I tested something else. This appears to still be a bug with RA.

I'm just going to remove the built in feature and do it all manually.

**Comment by trapexit** [comment]
OK... #168 should fix all this and expands on the NVRAM saving feature. You still have "per game" and "shared". "per game" is now managed by the core same as "shared" was which works around the "no_game_support" feature the core uses which caused the "per game" issue. In addition all nvrams can have 10 different versions. The old versions will be picked up should they be found but written as the new version.
